library(dplyr)
power_consumption <- read.csv("./household_power_consumption.txt",sep=";")
power_consumption$Date <- as.Date(power_consumption$Date,format="%d/%m/%Y")
Two_Days <- filter(power_consumption,Date=="2007-02-01"|Date=="2007-02-02")
Two_Days$Datetime <- strptime(paste(Two_Days$Date,Two_Days$Time),format="%Y-%m-%d %H:%M:%S")
png(filename = "Plot3.png")
plot(x=Two_Days$Datetime,y=as.numeric(Two_Days$Sub_metering_1),type="l",xlab="",ylab="Energy submetering")
lines(x=Two_Days$Datetime,y=as.numeric(Two_Days$Sub_metering_2),col="red")
lines(x=Two_Days$Datetime,y=as.numeric(Two_Days$Sub_metering_3),col="blue")
legend("topright",legend=c("Submetering 1","Submetering 2","Submetering 3"),col=c("black","red","blue"),lwd=4,bty="n")
dev.off()