library(dplyr)
power_consumption <- read.csv("./household_power_consumption.txt",sep=";")
power_consumption$Date <- as.Date(power_consumption$Date,format="%d/%m/%Y")
power_consumption$Datetime <- strptime(paste(power_consumption$Date,power_consumption$Time),format="%Y-%m-%d %H:%M:%S")
Two_Days <- filter(power_consumption,Date=="2007-02-01"|Date=="2007-02-02")
png(filename = "Plot4.png")
par(mfrow=c(2,2))
with(Two_Days,plot(x=Datetime,y=Global_active_power,type="l",ylab="Global Active Power",xlab=""))
with(Two_Days,plot(x=Datetime,y=Voltage,type="l",ylab="Voltage"))
with(Two_Days,plot(x=Datetime,y=as.numeric(Two_Days$Sub_metering_1),type="l",ylab="Energy submetering",xlab=""))
with(Two_Days,lines(x=Datetime,y=as.numeric(Sub_metering_2),col="red"))
with(Two_Days,lines(x=Datetime,y=as.numeric(Sub_metering_3),col="blue"))
with(Two_Days,legend("topright",legend=c("Submetering 1","Submetering 2","Submetering 3"),col=c("black","red","blue"),lwd=2,bty="n"))
with(Two_Days,plot(x=Datetime,y=Global_reactive_power,type="l",ylab="Global Reactive Power"))
dev.off()